import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SessionDetail } from "../medical-agent/[sessionId]/page";
import moment from "moment";
import { report } from "process";
type Props = {
  record: SessionDetail;
};
function ViewReportDialog({ record }: Props) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant={"link"} size={"sm"}>
          View Report
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle asChild>
            <h2 className="text-center text-4xl">
              Medical AI Voice gent Report
            </h2>
          </DialogTitle>
          <DialogDescription asChild>
            <div className="mt-10" key={record.id}>
              <h2 className="font-bold text-blue-500 text-lg"> Visit Info:</h2>
                <hr className="py-2"/>
              <div className="grid grid-cols-2">
                
                    <h2> <span className="font-bold">Doctor :</span> {record.selectedDoctor?.specialist}</h2>
                    <h2><span className="font-bold">Consult Date:</span> {moment(new Date(record?.createdOn)).fromNow()}</h2>

              </div>
               
               <div>
                  <h2 className="font-bold text-blue-500 text-lg pt-2"> Chief Complaint</h2>
                  <hr className="py-1"/>

                <span>{record.notes}</span>
               </div>
               {/* summary */}
                <div>
                    <h2 className="font-bold text-blue-500 text-lg pt-2">Summary</h2>
                    <hr className="py-1"/>
                    <span>{record.selectedDoctor?.description}</span>
                </div>
                {/* symptoms */}
                {/* <div>
                    <h2 className="font-bold text-blue-500 text-lg pt-2">User ID</h2>
                    <hr className="py-1"/>
                    <span>{record.selectedDoctor.}</span>
                </div> */}
                <div className="text-center justify-items-center">
                   <hr className="py-1"/>
                    <span className="text-sm  text-gray-400">This report was generated by AI Medical Assitant for information purposes</span>
                </div>

            </div>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;
